### ISSUE TITLE
Add button to enable opening log files of current run

### ISSUE THREAD

**Issue by hvdwolf** [MuseosAbiertos/csv2exif#3]
Feature?
It should have a disabled button between "write EXIF metadata" and "Close" called "Open Logs" or "View logs".
Once the script has finished, the button will be enabled to give the user the option to open the error and success log for that run in the default text editor.
When loading a new csv of new folder path it should be disabled again.

I will have a look in the coming days.

**Comment by hvdwolf** [comment]
Created it.
also created a checkbox "Empty output window before next run"  (default: True) below the output window.
If users want to continue with filling the output window instead of starting clean, they have now the option
And created a filemask on the file browse to only allow csv files

**Comment by mrtngrsbch** [comment]
cool, nice function
